apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: goapp241112 
  janus-idp.io/tekton: goapp241112
  backstage.io/kubernetes-id: goapp241112
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: goapp241112
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  