apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: goapp241112-gitops
  description: This is GitOps manifest for goapp241112   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: goapp241112
    backstage.io/kubernetes-id: goapp241112 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: goapp241112-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:goapp241112
